---
title: "Homework4 by Pranav Nair, ST558"
format: html
editor: visual
---

##Task 1

1)  What is the purpose of the lapply() function?
2)
3)
4)


##Task 2

```{r}
library(dplyr)
library(tidyr)

#1 create an RMSE function
getRMSE <- function(responses, predictions, ...) {
  
  
  sqrt(mean((responses-predictions)^2, ...))
  # yminusyhat <- (responses - predictions)^2
  # 
  # meanyminusyhat <- mean(yminusyhat)
  # 
  # rmse <- sqrt(meanyminusyhat)
  
  
}

#2 Run following code to create response values and predictions.

set.seed(10)
n <- 100
x <- runif(n)
resp <- 3 + 10*x + rnorm(n)
pred <- predict(lm(resp ~ x), data.frame(x))
resp

#now to replace two numbers in the numerical vector with "na" values.

respNA <- resp

NA_stuff <- sample(1:n, 2)
respNA[NA_stuff] <- NA_real_

RMSE_regular <- getRMSE(resp, pred)
print(RMSE_regular)

RMSE_NA <- getRMSE(respNA, pred)
print(RMSE_NA)

respNA

RMSE_NA_remove <- getRMSE(respNA, pred, na.rm = TRUE)
print(RMSE_NA_remove)


#3 MAE function
getMAE <- function(responses, predictions, ...) {
  (1/n)*(mean(abs(responses - predictions),...))
}

#4 Run the following code to create some response values and predictions.
set.seed(10)
n <- 100
x <- runif(n)
resp <- 3 + 10*x + rnorm(n)
pred <- predict(lm(resp ~ x), data.frame(x))

getMAE(resp, pred)


respNA <- resp
NA_stuff <- sample(1:n, 2)
respNA[NA_stuff] <- NA_real_


MAE_regular <- getMAE(resp, pred)
print(MAE_regular)
MAE_NA <- getMAE(respNA, pred)
print(MAE_NA)
MAE_NA_ignore <- getMAE(respNA, pred, na.rm = TRUE)
print(MAE_NA_ignore)


#5 Create a wrapper function that can be used to get either or both metrics with one single function call. 

wrapper_function <- function(responses, predictions, metrics = c("RMSE", "MAE"), ...) {
  
  if(!(is.vector(responses) && 
       is.atomic(responses) && 
       is.numeric(responses) &&
       is.vector(predictions) &&
       is.atomic(predictions) &&
       is.numeric(predictions))) {
    message("Error!")
    return(NULL)
  }
  
results <- list()

if("RMSE" %in% metrics) {
  results$RMSE <- getRMSE(responses, predictions)
}

if("MAE" %in% metrics){
  results$MAE <- getMAE(responses, predictions)
}

return(results)
}

wrapper_function(resp, pred, na.rm = TRUE)


#6
set.seed(10)
n <- 100
x <- runif(n)
resp <- 3 + 10*x + rnorm(n)
pred <- predict(lm(resp ~ x), data.frame(x))


#call wrapper function for RMSE metric only
RMSE_result <- wrapper_function(resp, pred, metrics = "RMSE")
print(RMSE_result)

#call wrapper function for MAE metric only
MAE_result <- wrapper_function(resp, pred, metrics = "MAE")
print(MAE_result)

#call wrapper function for both metrics
both_result <- wrapper_function(resp, pred)
print(both_result)


#replace two of the response values with missing values (NA_real_)
respNA <- resp

NA_stuff <- sample(1:n, 2)
respNA[NA_stuff] <- NA_real_

NA_result <- wrapper_function(respNA, pred)
print(NA_result)


#Test the function by passing incorrect data, in this case it will be a character vector

incorrect_data <- c("one", "two", "three")

incorrect_result <- wrapper_function(incorrect_data, pred)


  
```

##Task 3 - Querying API and Tidy-style function

API Key - 3d1f81a3ce154208b6381c8654231a99

```{r}
library(httr)
library(tidycensus)

url_api <- "https://newsapi.org/v2/everything?q=tesla&from=2024-05-24&sortBy=publishedAt&apiKey=3d1f81a3ce154208b6381c8654231a99"

id_info <- GET(url_api)
str(id_info, max.level = 1)

load_data_api <- function(url_api, date, api_key) {
  url_api <- paste0("https://newsapi.org/v2/everything?q=tesla&from=2024-05-24&sortBy=publishedAt&apiKey=3d1f81a3ce154208b6381c8654231a99")
  
  
}
```

